version: '3'

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - turbo
    restart: always

  turbo:
    container_name: turbo
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports: 
      - "5173:3000"
      - "3000:3000"
    networks:
      - turbo
    depends_on:
      - postgres
    volumes: 
      - ./apps/backend:/ft_transcendence/apps/backend
      - ./apps/frontend:/ft_transcendence/apps/frontend
    env_file:
      - .env.prod
    restart: always

networks:
  turbo:
    driver: bridge

